version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-web-server
    env_file: .env
    depends_on:
      - mysql
      - redis
    command: ./wait-for-it.sh mysql:3306 -t 0 -- npm start
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app

  mysql:
    image: 'mysql:5.7'
    command: --default-time-zone=${TIMEZONE} --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '2705:3306'
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: 'redis'
    ports:
      - '2706:6379'
    volumes:
      - ./data/redis:/data
