import Sequelize from "sequelize";

const Op = Sequelize.Op;
const operatorsAliases = {
  $eq: Op.eq,
  $ne: Op.ne,
  $gte: Op.gte,
  $gt: Op.gt,
  $lte: Op.lte,
  $lt: Op.lt,
  $not: Op.not,
  $in: Op.in,
  $notIn: Op.notIn,
  $is: Op.is,
  $like: Op.like,
  $notLike: Op.notLike,
  $iLike: Op.iLike,
  $notILike: Op.notILike,
  $regexp: Op.regexp,
  $notRegexp: Op.notRegexp,
  $iRegexp: Op.iRegexp,
  $notIRegexp: Op.notIRegexp,
  $between: Op.between,
  $notBetween: Op.notBetween,
  $overlap: Op.overlap,
  $contains: Op.contains,
  $contained: Op.contained,
  $adjacent: Op.adjacent,
  $strictLeft: Op.strictLeft,
  $strictRight: Op.strictRight,
  $noExtendRight: Op.noExtendRight,
  $noExtendLeft: Op.noExtendLeft,
  $and: Op.and,
  $or: Op.or,
  $any: Op.any,
  $all: Op.all,
  $values: Op.values,
  $col: Op.col,
};

export default {
  host: process.env.MYSQL_HOST || "localhost",
  username: process.env.MYSQL_USERNAME || "default_username",
  password: process.env.MYSQL_PASSWORD || "default_password",
  database: process.env.MYSQL_DATABASE || "default_database",
  dialect: "mysql",
  migrationStorage: "sequelize",
  migrationStorageTableName: "z_sequelize_migrations",
  seederStorage: "sequelize",
  seederStorageTableName: "z_sequelize_seeders",
  operatorsAliases,
  logging: false,
  timezone: "+00:00",
  define: {
    charset: "utf8mb4",
    collate: "utf8mb4_general_ci",
    timestamps: false,
    underscored: true,
    freezeTableName: true,
  },
  use_env_variable: null,
};
